#+TITLE: Technical Wrtiting and Speaking in English

* About
This repository holds the material used for the course Technical Writing and
Speaking in English of the [[https://mosig.imag.fr/][M1 MOSIG]] at [[https://im2ag.univ-grenoble-alpes.fr/en/][University Grenoble Alpes]].

* Contributors
- [[https://danilo-carastan-santos.github.io/][Danilo Carastan-Santos]]
- [[https://www.linkedin.com/in/kevi-eniko/][Enikő Kevi]]
- [[https://andersonandrei.github.io/][Anderson Andrei da Silva]]
- [[https://guilloteauq.github.io/][Quentin Guilloteau]]

* Repository Structure
- sessions: holds the course material for each year and city we ran the course.

* Course objectives

The course aims to help the student with the following skills:
- Develop the ability to create well-formatted documents using LaTeX 
- Understand the basic structure of a scientific document and its writing conventions
- Develop writing techniques to write clear, convincing, and energetic scientific documents
- Be more comfortable when presenting scientific content to an audience

* References
- Alley, M. (2018). The Craft of Scientific Writing. Springer New
  York. https://doi.org/10.1007/978-1-4419-8288-9

- Alley, M. (2013). The Craft of Scientific Presentations: Critical Steps to
  Succeed and Critical Errors to Avoid. Springer New
  York. https://doi.org/10.1007/978-1-4419-8279-7
