#+TITLE: Technical Wrtiting and Speaking in English - 2023-2024 session

* About
This page holds the material used for the course Technical Writing and Speaking
in English of the [[https://mosig.imag.fr/][M1 MOSIG]] at
[[https://im2ag.univ-grenoble-alpes.fr/en/][University Grenoble Alpes]] during
the 2023-2024 session.

* Teachers
- [[https://danilo-carastan-santos.github.io/][Danilo Carastan-Santos]]: danilo.carastan-dos-santos@inria.fr
- [[https://www.linkedin.com/in/kevi-eniko/][Enikő Kevi]]: eniko.kevi@univ-grenoble-alpes.fr

* Course objectives
You will be training the following skills by following this course.

** 1. Writing Basic skills
      - *Clarity and Precision:* Develop the ability to convey complex scientific
         concepts with clarity and precision.
      - *Conciseness:* Develop the ability to convey ideas concisely without
         sacrificing clarity. Practice eliminating unnecessary words and
         redundancy.
      - *Structure and Organization:* Understand the importance of
         well-structured writing. Learn how to craft clear introductions,
         well-organized main sections, and conclusive summaries.
      - *Abstracts, Summaries and Titles:* Learn how to write effective
        abstracts, summaries and titles that capture the essence of your work
        and entice readers to explore further.
      - *Audience Awareness:* Understand the importance of tailoring your
        writing to your intended audience, whether it's fellow scientists,
        educators, or the general public.

** 2. Synthesis
      - *Arguement Development:* Learn to formulate clear and concise narrative
        that guides the reader through your work.
      - *Critical Thinking:* Enhance your critical thinking skills by evaluating
        and synthesizing existing research, identifying gaps, and formulating
        evidence-based arguments.
      - *Data Presentation:* Learn to effectively present and interpret data
        through graphs, tables, and figures. Understand how visuals enhance the
        understanding of scientific findings.

** 3. Writing Tools
      - *LaTeX:* Develop the ability to write documents using LaTeX, know how to
        structure sections, to add figures and equations, and to add proper
        citation.
      - *Grammar tools and Writing Assistants:* Understand the advantages and
        limitations of grammar tools and writing assistants (e.g., Grammarly,
        LanguageTool, ChatGPT). Learn whether is appropriate or not to use these
        tools.
      - *Presentation Tools:* Get an overal view of available presentation tools
        (e.g., Prezi, Google Slides, Beamer).

** 4. Hands-on Experience
      - *Revision and Editing:* Gain experience in revising and editing. Recognize
        the importance of multiple drafts and peer review in improving the
        quality of your writing.
      - *Collaborative Writing:* Gain experience in collaborative writing
        through group projects, learning to work together to create a cohesive
        and well-structured document.

** 5. Speaking to an Audience
      - *Anxiety Management:* Be comfortable to presenting ideas and research
        work to an audience
      - *Bad Habits Awareness:* Know common speaking and presentation bad habits
        and critital errors and how to avoid them.

* Course Schedule and Evaluation Process
** Schedule
You may find the schedule for all courses in M1 MOSIG at the
[[https://ade-uga-ro-vs.grenet.fr/direct/index.jsp?data=5e58d6dfb7fba2eadbc98b822b5605b3740ced8a164c508d9e913f703ae44e271acc0d115c463861acfc36b866baffb5d334c10559d5088c20ada3e85f74b6a618f9ce92d9857ec7783739e27d2592fdce5d016527fea8754e9b0d9404c94c20,1][ADE
Webpage]]. The table below presents a tentative schedule for this course.

| Week | Date       | Content                                               |
|------+------------+-------------------------------------------------------|
|    1 | 15/09/2023 | Course presentation and tools for scientific writing  |
|    2 | 22/09/2023 | Writing clear and concise text                        |
|    3 | 29/09/2023 | Writing a research methodology                        |
|    4 | 06/10/2023 | Writing scientific results                            |
|    5 | 13/10/2023 | Wrapping up a conclusion                              |
|    6 | 20/10/2023 | Writing an introduction                               |
|    7 | 27/10/2023 | Writing an Abstract and a Title                       |
|    8 | 10/11/2023 | Mid-term exam                                         |
|    9 | 17/11/2023 | Presenting scientific content (speaking)              |
|   10 | 24/11/2023 | Preparing good slides and practicing the presentation |
|   11 | 01/12/2023 | Hands-on student presentations                        |

** Evaluation Process
1. *Mid-term exam (MT):* 50%
2. *Student presentations (SP):* 40%
3. *Attendance to the classes: (ATT)* 10%

*Final Grade =* 0.5*MT + 0.1*ATT + 0.4*SP

* References
- Alley, M. (2018). The Craft of Scientific Writing. Springer New
  York. https://doi.org/10.1007/978-1-4419-8288-9

- Alley, M. (2013). The Craft of Scientific Presentations: Critical Steps to
  Succeed and Critical Errors to Avoid. Springer New
  York. https://doi.org/10.1007/978-1-4419-8279-7
